stages:
  - build
  - test
  - sonarqube-check
  - trigger_deploy

build:
  stage: build
  script:
    - ./gradlew assemble --no-daemon

test:
  stage: test
  script:
    - ./gradlew test --no-daemon

sonarqube-check:
  stage: sonarqube-check
  script:
    - echo "Backend..."

trigger_deploy:
  stage: trigger_deploy
  rules:
    - if: '$CI_COMMIT_BRANCH == "main"'
  trigger:
    project: projects/group-infra
    branch: main